AlignAfterOpenBracket: DontAlign
AlignConsecutiveMacros: "true"
AlignConsecutiveAssignments: "true"
AlignConsecutiveDeclarations: "true"
AlignEscapedNewlines: Left
AlignOperands: "false"
AlignTrailingComments: "true"
AllowAllConstructorInitializersOnNextLine: "false"
AllowShortBlocksOnASingleLine: "true"
AllowShortCaseLabelsOnASingleLine: "true"
AllowShortFunctionsOnASingleLine: Inline
AllowShortIfStatementsOnASingleLine: WithoutElse
AllowShortLambdasOnASingleLine: All
AllowShortLoopsOnASingleLine: "true"
AlwaysBreakAfterReturnType: None
AlwaysBreakBeforeMultilineStrings: "true"
BreakAfterJavaFieldAnnotations: "false"
BreakBeforeBinaryOperators: None
BreakBeforeBraces: WebKit
BreakBeforeTernaryOperators: "false"
BreakConstructorInitializers: BeforeComma
BreakInheritanceList: BeforeComma
BreakStringLiterals: "false"
ColumnLimit: "120"
CompactNamespaces: "false"
ConstructorInitializerAllOnOneLineOrOnePerLine: "false"
Cpp11BracedListStyle: "true"
FixNamespaceComments: "true"
IncludeBlocks: Merge
IndentCaseLabels: "false"
IndentPPDirectives: BeforeHash
IndentWidth: "4"
KeepEmptyLinesAtTheStartOfBlocks: "false"
Language: Cpp
ObjCSpaceAfterProperty: "false"
ObjCSpaceBeforeProtocolList: "false"
PointerAlignment: Right
ReflowComments: "true"
SortIncludes: "false"
SortUsingDeclarations: "true"
SpaceAfterCStyleCast: "true"
SpaceAfterLogicalNot: "false"
SpaceAfterTemplateKeyword: "true"
SpaceBeforeAssignmentOperators: "true"
SpaceBeforeCpp11BracedList: "true"
SpaceBeforeCtorInitializerColon: "true"
SpaceBeforeInheritanceColon: "true"
SpaceBeforeParens: ControlStatements
SpaceBeforeRangeBasedForLoopColon: "true"
SpaceInEmptyParentheses: "false"
SpacesBeforeTrailingComments: "2"
SpacesInAngles: "false"
SpacesInCStyleCastParentheses: "false"
SpacesInContainerLiterals: "false"
SpacesInParentheses: "false"
SpacesInSquareBrackets: "false"
Standard: Cpp11
TabWidth: "4"
UseTab: ForContinuationAndIndentation
